default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("PGHOST", "db") %>
  username: <%= ENV.fetch("PGUSER", "postgres") %>
  password: <%= ENV.fetch("PGPASSWORD", "password") %>

development:
  <<: *default
  database: sotuapp_development

test:
  <<: *default
  database: sotuapp_test

production:
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>
